"""user_grade

Revision ID: 0b7a406ddf09
Revises: ab1a3236c27b
Create Date: 2023-09-17 23:28:25.013287

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0b7a406ddf09'
down_revision = 'ab1a3236c27b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('grade', sa.String(), nullable=True))
    op.add_column('users', sa.Column('no_grade_ok', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'grade')
    op.drop_column('users', 'no_grade_ok')
    # ### end Alembic commands ###
