"""add language column to channel model

Revision ID: 5c8dcc2c48ff
Revises: 39b407d205ff
Create Date: 2025-01-26 00:57:54.706080

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy_utils.types.choice import ChoiceType

from bot.schemas import Grades

# revision identifiers, used by Alembic.
revision = '5c8dcc2c48ff'
down_revision = '39b407d205ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('language', ChoiceType(Grades), nullable=True))
    op.execute(sa.text("UPDATE channels set language='python'"))
    op.alter_column('channels', 'language', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'language')
    # ### end Alembic commands ###
