"""added vacancy model

Revision ID: 89c2dc4f227a
Revises: 74fe4e4918d0
Create Date: 2026-01-07 08:21:29.045990

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy_utils.types.choice import ChoiceType

from bot.schemas import VacancySource

# revision identifiers, used by Alembic.
revision = '89c2dc4f227a'
down_revision = '74fe4e4918d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('cv', 'resume')
    op.create_table(
        'vacancy',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('source', ChoiceType(VacancySource), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', 'user_id', 'source'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancy')
    op.rename_table('resume', 'cv')
    # ### end Alembic commands ###
