"""create SearchItem model

Revision ID: bcfedcd90fa6
Revises: e31de5ce64dd
Create Date: 2025-01-04 23:22:27.772365

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy_utils import ChoiceType

from bot.schemas import Grades, Languages

# revision identifiers, used by Alembic.
revision = 'bcfedcd90fa6'
down_revision = 'e31de5ce64dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'searchitems',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('grade', ChoiceType(Grades), nullable=False),
        sa.Column('language', ChoiceType(Languages), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('searchitems')
    # ### end Alembic commands ###
