"""added two-fields pk to Channels table

Revision ID: d7ba8d11ba21
Revises: 5c8dcc2c48ff
Create Date: 2025-02-02 17:27:04.135353

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = 'd7ba8d11ba21'
down_revision = '5c8dcc2c48ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('channels_name_key', 'channels', type_='unique')
    op.drop_constraint('channels_pkey', table_name='channels')
    op.drop_index('ix_channels_id', table_name='channels')
    op.create_primary_key('channels_pkey', table_name='channels', columns=['id', 'language'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('channels_pkey', 'channels')
    op.create_index('ix_channels_id', 'channels', ['id'])
    op.create_primary_key('channels_pkey', table_name='channels', columns=['id'])
    op.create_unique_constraint('channels_name_key', 'channels', ['name'])
    # ### end Alembic commands ###
